project:
  type: website
  output-dir: docs

website:
  title: "Suhas Thalanki"
  search: false
  navbar:
    background: dark
    right:
      - blog.qmd
      - text: Resume
        href: https://drive.google.com/file/d/1o0Mn5dWp8wx4rJGniCEtxft4au9BZZxZ/view?usp=share_link
      - icon: github
        href: https://github.com/thesuhas
      - icon: linkedin
        href: https://www.linkedin.com/in/suhas-thalanki/

format:
  html:
    theme: darkly
    css: styles.css