project:
  type: website
  output-dir: docs

website:
  title: "Suhas Thalanki"
  search: false
  navbar:
    background: dark
    right:
      - blog.qmd
      - text: Resume
        href: https://drive.google.com/file/d/1LZHt5nepc2-ust_E_hLYXR5II4clO91G/view?usp=sharing
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/suhas-thalanki/

format:
  html:
    theme: darkly
    css: styles.css



